devices:
  - name: 'main'
    ip: '192.168.0.*'
    mac: 'A0:B1:C2:D3:E4:F5'

bot: # telegram bot token
  token: "token from https://t.me/botfather"
  admins: 
    - 1234567890

settings: # application settings
  debug: true
  timezone: "GMT+3"