name: Build native binaries
on:
  push:
    paths-ignore:
      - example.config.yaml
      - .gitignore
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
        os: [ linux ]

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Shorten Commit Hash
        id: short_hash
        run: echo "HASH=${GITHUB_SHA:0:7}" >> "$GITHUB_OUTPUT"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23.2'

      - name: Build for ${{ matrix.architecture }}
        run: |
          go mod download -x
          GOARCH=${{ matrix.architecture }} go build -o wol-e-${{ matrix.architecture }} cmd/main.go
          
      - name: Publish Release
        id: publish_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            wol-e-amd64
            wol-e-arm64
          tag_name: ${{ steps.short_hash.outputs.HASH }}
          name: ${{ github.event.head_commit.message }}
          body: Release for commit ${{ steps.short_hash.outputs.HASH }}
